services:
  mysql:
    image: mysql:8.0
    container_name: recipevault-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword} #rootpassword will be default value passed if no .env file is present
      MYSQL_DATABASE: recipevault
      MYSQL_USER: ${MYSQL_USERNAME:-recipeuser} #recipeuser will be default value passed if no .env file is present
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-recipepass} #recipepass will be default value passed if no .env file is present
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - recipevault-network

  backend:
    build: ./backend
    container_name: recipevault-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${ENVIRONMENT:-dev}
      MYSQL_USERNAME: ${MYSQL_USERNAME:-recipeuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-recipepass}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/recipevault?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      JAVA_OPTS: ${JAVA_OPTS:--Xmx256m -Xms128m}
    ports:
      - "9000:9000"
    networks:
      - recipevault-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./recipe-vault-frontend
    container_name: recipevault-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - recipevault-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mysql-data:

networks:
  recipevault-network:
    driver: bridge
