import { Recipe } from '../types/recipe';

// Sample recipe data
export const recipeData: Recipe[] = [
  {
    id: 3,
    title: 'Italian Carbonara #3',
    difficulty: 'MEDIUM',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 3: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1003',
    creatorName: 'DefaultUser',
    createdDate: '2025-05-22T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 4,
    title: 'Classic Carbonara #4',
    difficulty: 'MEDIUM',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 4: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1004',
    creatorName: 'DefaultUser',
    createdDate: '2025-05-23T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 5,
    title: 'Traditional Carbonara #5',
    difficulty: 'HARD',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 5: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1005',
    creatorName: 'DefaultUser',
    createdDate: '2025-05-24T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 6,
    title: 'Creamy Carbonara #6',
    difficulty: 'EASY',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 6: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1006',
    creatorName: 'DefaultUser',
    createdDate: '2025-05-25T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 7,
    title: 'Spaghetti Carbonara #7',
    difficulty: 'MEDIUM',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 7: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1007',
    creatorName: 'DefaultUser',
    createdDate: '2025-05-26T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 8,
    title: 'Traditional Carbonara #8',
    difficulty: 'HARD',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 8: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1008',
    creatorName: 'DefaultUser',
    createdDate: '2025-05-27T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 9,
    title: 'Spaghetti Carbonara #9',
    difficulty: 'EASY',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 9: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1009',
    creatorName: 'DefaultUser',
    createdDate: '2025-05-28T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 10,
    title: 'Italian Carbonara #10',
    difficulty: 'HARD',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 10: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1010',
    creatorName: 'DefaultUser',
    createdDate: '2025-05-29T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 11,
    title: 'Creamy Carbonara #11',
    difficulty: 'EASY',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 11: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1011',
    creatorName: 'DefaultUser',
    createdDate: '2025-05-30T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 12,
    title: 'Spaghetti Carbonara #12',
    difficulty: 'EASY',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 12: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1012',
    creatorName: 'DefaultUser',
    createdDate: '2025-05-31T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 13,
    title: 'Creamy Carbonara #13',
    difficulty: 'EASY',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 13: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1013',
    creatorName: 'DefaultUser',
    createdDate: '2025-06-01T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 14,
    title: 'Creamy Carbonara #14',
    difficulty: 'MEDIUM',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 14: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1014',
    creatorName: 'DefaultUser',
    createdDate: '2025-06-02T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 15,
    title: 'Traditional Carbonara #15',
    difficulty: 'EASY',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 15: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1015',
    creatorName: 'DefaultUser',
    createdDate: '2025-06-03T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 16,
    title: 'Spaghetti Carbonara #16',
    difficulty: 'HARD',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 16: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1016',
    creatorName: 'DefaultUser',
    createdDate: '2025-06-04T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 17,
    title: 'Italian Carbonara #17',
    difficulty: 'MEDIUM',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 17: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1017',
    creatorName: 'DefaultUser',
    createdDate: '2025-06-05T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 18,
    title: 'Creamy Carbonara #18',
    difficulty: 'MEDIUM',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 18: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1018',
    creatorName: 'DefaultUser',
    createdDate: '2025-06-06T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 5,
  },
  {
    id: 19,
    title: 'Spaghetti Carbonara #19',
    difficulty: 'MEDIUM',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 19: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1019',
    creatorName: 'DefaultUser',
    createdDate: '2025-06-07T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 12,
  },
  {
    id: 20,
    title: 'Traditional Carbonara #20',
    difficulty: 'HARD',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 20: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1020',
    creatorName: 'DefaultUser',
    createdDate: '2025-06-08T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 8,
  },
  {
    id: 21,
    title: 'Italian Carbonara #21',
    difficulty: 'HARD',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 21: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1021',
    creatorName: 'DefaultUser',
    createdDate: '2025-06-09T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 20,
  },
  {
    id: 22,
    title: 'Creamy Carbonara #22',
    difficulty: 'MEDIUM',
    instructions:
      '1. Cook pasta. 2. Fry bacon. 3. Mix eggs and cheese. 4. Combine all ingredients. Step 22: Serve hot.',
    imageUrl: 'https://picsum.photos/400/250?random=1022',
    creatorName: 'DefaultUser',
    createdDate: '2025-06-10T21:22:51.683597',
    ingredients: [
      { id: 6, ingredientName: 'spaghetti' },
      { id: 7, ingredientName: 'eggs' },
      { id: 8, ingredientName: 'bacon' },
      { id: 9, ingredientName: 'parmesan cheese' },
      { id: 10, ingredientName: 'black pepper' },
    ],
    ingredientCount: 7,
  },
];

// Get a fresh copy to avoid direct mutations
export const getInitialRecipeData = (): Recipe[] => {
  return JSON.parse(JSON.stringify(recipeData));
};
