package com.recipevault.backend.mapper;

import com.recipevault.backend.dto.recipes.RecipeCreateDTO;
import com.recipevault.backend.dto.recipes.RecipeDetailDTO;
import com.recipevault.backend.dto.recipes.RecipeSummaryDTO;
import com.recipevault.backend.dto.recipes.RecipeUpdateDTO;
import com.recipevault.backend.entities.IngredientEntity;
import com.recipevault.backend.entities.RecipeEntity;
import org.mapstruct.AfterMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

import java.util.List;

/*
 * Mapper class responsible for converting between domain entities and DTOs used to transfer data between layers
 * Seperation of concerns -> internal domain model (entities) decoupled from data structures exposed to client
 * Data shaping -> controls exactly what data is exposed via API
 * Reusability -> Centralize mapping logic
 * Adaptability -> Change internal models or API independently as long as Mapper updated
 */

// Uses IngredientMapper when mapping Ingredient objects within a Recipe
@Mapper(componentModel = "spring", uses = {IngredientMapper.class})
public interface RecipeMapper {

    // Calculates ingredientCount on the fly for lightweight DTO with summary info
    @Mapping(target = "ingredientCount", expression = "java(recipe.getIngredients().size())")
    @Mapping(target = "userId", source = "user.id")
    RecipeSummaryDTO toSummaryDTO(RecipeEntity recipe);

    List<RecipeSummaryDTO> toSummaryDTOList(List<RecipeEntity> recipes);

    // DTO with all recipe details, Mapstruct automatically uses IngredientMapper to convert Ingredients list
    @Mapping(target = "userId", source = "user.id")
    RecipeDetailDTO toDetailDTO(RecipeEntity recipe);

    // Ingredients filed handled separately and id is generated by database
    @Mapping(target = "ingredients", ignore = true)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdDate", expression = "java(java.time.LocalDateTime.now())")
    @Mapping(target = "imageUrl", source = "imageUrl")
    RecipeEntity toEntity(RecipeCreateDTO dto);

    // Maps data from RecipeUpdateDTO to existing recipe entity, only updating fields present in DTO
    @Mapping(target = "ingredients", ignore = true)
    @Mapping(target = "id", ignore = true)
    void updateRecipeFromDTO(RecipeUpdateDTO dto, @MappingTarget RecipeEntity recipe);

    // Executes after automatic mapping
    // Handles complex relationships
    // Extracts ingredient names from DTO and create new ingredient entities
    @AfterMapping
    default void mapIngredients(RecipeCreateDTO dto, @MappingTarget RecipeEntity recipe) {
        if (dto.getIngredientNames() != null) {
            dto.getIngredientNames().forEach(name -> {
                IngredientEntity ingredient = new IngredientEntity();
                ingredient.setIngredientName(name);
                recipe.addIngredient(ingredient);
            });
        }
    }

    @AfterMapping
    default void mapIngredients(RecipeUpdateDTO dto, @MappingTarget RecipeEntity recipe) {
        if (dto.getIngredientNames() != null) {
            dto.getIngredientNames().forEach(name -> {
                IngredientEntity ingredient = new IngredientEntity();
                ingredient.setIngredientName(name);
                recipe.addIngredient(ingredient);
            });
        }
    }

}

